# Generated by Django 3.2.25 on 2025-03-16 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='products',
            table='produtos',
        ),
    ]
