# Generated by Django 3.2.25 on 2025-08-17 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='pid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
