# Generated by Django 3.2.25 on 2025-07-06 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20250421_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='imagens',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/'),
        ),
    ]
