# Generated by Django 3.2.25 on 2025-07-06 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_products_imagens'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='imagens',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/'),
        ),
    ]
